- id: doi:10.1093/bfgp/elae042
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2024-10-22
  buttons:
    - type: website
      link: https://academic.oup.com/bfg/article-abstract/doi/10.1093/bfgp/elae042/7831150
  tags:
    - machine learning
    - brain age
  repo: wanglab/brainage-review

- id: 10.1371/journal.pone.0076105

- id: 10.1111/adb.12644

- id: 10.1002/hbm.23146

- id: 10.1101/2024.11.12.623073

- id: 10.1038/s41598-020-65086-x

- id: 10.1007/s11517-013-1131-9

- id: 10.1038/srep18969

- id: doi:10.3389/fnsys.2012.00063
